name: Dump Secrets

on:
  workflow_dispatch:

jobs:
  dump-secrets:
    runs-on: ubuntu-latest
    steps:

      - name: Save secrets to file
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          APPLE_CONNECT_EMAIL: ${{ secrets.APPLE_CONNECT_EMAIL }}
          APPLE_DEVELOPER_EMAIL: ${{ secrets.APPLE_DEVELOPER_EMAIL }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          GOOGLE_PLAY_KEY_FILE: ${{ secrets.GOOGLE_PLAY_KEY_FILE }}
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          ANDROID_KEYALIAS_NAME: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          ANDROID_KEYALIAS_PASS: ${{ secrets.ANDROID_KEYALIAS_PASS }}
          ANDROID_PACKAGE_NAME: ${{ secrets.ANDROID_PACKAGE_NAME }}
          IOS_BUNDLE_ID: ${{ secrets.IOS_BUNDLE_ID }}
          MATCH_REPOSITORY: ${{ secrets.MATCH_REPOSITORY }}
          MATCH_DEPLOY_KEY: ${{ secrets.MATCH_DEPLOY_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_P8: ${{ secrets.APPSTORE_P8 }}
          GH_PAT: ${{ secrets.GH_PAT }}

        run: |
          echo "UNITY_EMAIL=${UNITY_EMAIL}" >> secrets.txt
          echo "UNITY_PASSWORD=${UNITY_PASSWORD}" >> secrets.txt
          echo "UNITY_SERIAL=${UNITY_SERIAL}" >> secrets.txt
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> secrets.txt
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> secrets.txt
          echo "APPLE_CONNECT_EMAIL=${APPLE_CONNECT_EMAIL}" >> secrets.txt
          echo "APPLE_DEVELOPER_EMAIL=${APPLE_DEVELOPER_EMAIL}" >> secrets.txt
          echo "APPLE_TEAM_ID=${APPLE_TEAM_ID}" >> secrets.txt
          echo "GOOGLE_PLAY_KEY_FILE=${GOOGLE_PLAY_KEY_FILE}" >> secrets.txt
          echo "ANDROID_KEYSTORE_BASE64=${ANDROID_KEYSTORE_BASE64}" >> secrets.txt
          echo "ANDROID_KEYSTORE_PASS=${ANDROID_KEYSTORE_PASS}" >> secrets.txt
          echo "ANDROID_KEYALIAS_NAME=${ANDROID_KEYALIAS_NAME}" >> secrets.txt
          echo "ANDROID_KEYALIAS_PASS=${ANDROID_KEYALIAS_PASS}" >> secrets.txt
          echo "ANDROID_PACKAGE_NAME=${ANDROID_PACKAGE_NAME}" >> secrets.txt
          echo "IOS_BUNDLE_ID=${IOS_BUNDLE_ID}" >> secrets.txt
          echo "MATCH_REPOSITORY=${MATCH_REPOSITORY}" >> secrets.txt
          echo "MATCH_DEPLOY_KEY=${MATCH_DEPLOY_KEY}" >> secrets.txt
          echo "MATCH_PASSWORD=${MATCH_PASSWORD}" >> secrets.txt
          echo "APPSTORE_ISSUER_ID=${APPSTORE_ISSUER_ID}" >> secrets.txt
          echo "APPSTORE_KEY_ID=${APPSTORE_KEY_ID}" >> secrets.txt
          echo "APPSTORE_P8=${APPSTORE_P8}" >> secrets.txt
          echo "GH_PAT=${GH_PAT}" >> secrets.txt


      - name: Upload secrets artifact
        uses: actions/upload-artifact@v4
        with:
          name: secrets
          path: secrets.txt
          retention-days: 1